version: '3'  
services:
  master:
    image: itzg/elasticsearch
    environment:
      TYPE: MASTER
      UNICAST_HOSTS: master
      MIN_MASTERS: 1
    deploy:
      placement:
        constraints: 
          - node.role == manager
      replicas: 1
      update_config:
        parallelism: 1
    ports:
      - "9200:9200"
      - "9300:9300"
  data:
    image: itzg/elasticsearch
    environment:
      TYPE: DATA
      UNICAST_HOSTS: master
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.labels.db == elasticsearch
      update_config:
        parallelism: 1
        delay: 60s
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://master:9200
    deploy:
      placement:
        constraints: 
          - node.role == manager
      