version: '3'  
services:
  master:
    image: itzg/elasticsearch
    environment:
      TYPE: MASTER
      UNICAST_HOSTS: master
      MIN_MASTERS: 1
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
  data:
    image: itzg/elasticsearch
    environment:
      TYPE: DATA
      UNICAST_HOSTS: master
        ES_JAVA_OPTS:"-Xms4g -Xmx4g"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 60s
        placement:
            constraints: [node.labels.db == elasticsearch]
  gateway:
    image: itzg/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      TYPE: GATEWAY
      UNICAST_HOSTS: master
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://gateway:9200